name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --forzen-lockfile

      - name: Build docs
        run: pnpm docs:build

      - name: Add .nojekyll
        run: echo > docs/.vuepress/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs/.vuepress/dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
